version: "3.3"

services:

  waffle:
    image: "${WAFFLE_TAG}"
    volumes:
    - staging:/mnt/waffle:rw
    env_file:
    - docker-compose.env

  tx_spammer:
    image: "${MICROSERVICES_TAG}"
    volumes:
    - staging:/mnt/waffle:r
    - staging:/mnt/spammer:rw
    env_file:
    - docker-compose.env

  postgres:
    image: "${POSTGRES_IMAGE}"
    volumes:
    - postgres:/var/lib/postgresql/data
    env_file:
    - docker-compose.env
    ports:
    - 5432:5432

  miner:
    image: "${MINER_IMAGE}"
    volumes:
    - miner:/mnt/data:rw
    env_file:
    - docker-compose.env
    ports:
    - 8545:8545

volumes:
  staging:
  miner:
  postgres:
