version: "3.3"

services:
  miner:
    build:
      context: ./geth
      dockerfile: Dockerfile
      args:
        GETH_REPO_URL: {GETH_REPO_URL}
        GETH_BRANCH_NAME: {GETH_BRANCH_NAME}
    volumes:
    - chain_testing_miner:/mnt/data:rw
    - ./geth/genesis.json:/mnt/data/genesis.json
    env_file:
    - ./docker-compose.env
    ports:
    - 8545:8545

  tx_spammer:
    depends_on:
      - miner
    image: {SPAMMER_IMAGE_URL}
    volumes:
    - chain_testing_spammer:/app:rw
    - ./spammer/config.toml:/app/environments/example.toml
    - ./spammer/test_abi.json:/app/abis/test_abi.json
    - ./keys:/app/keys
    env_file:
    - ./docker-compose.env

volumes:
  chain_testing_spammer:
  chain_testing_miner:
